/*
    수강신청


*/

DROP TABLE ENROLL;
DROP TABLE STUDENT;
DROP TABLE SUBJECT;

CREATE TABLE STUDENT(
    STU_NO CHAR(5 BYTE) NOT NULL PRIMARY KEY,
    STU_NAME VARCHAR2(20 BYTE) NOT NULL,
    STU_AGE NUMBER(2) NOT NULL
);

CREATE TABLE SUBJECT(
    SUB_CODE CHAR(1) NOT NULL PRIMARY KEY,
    SUB_NAME VARCHAR2(30 BYTE) NOT NULL,
    PRO_NAME VARCHAR2(30 BYTE) NOT NULL
);

CREATE TABLE ENROLL(
    ENR_NO NUMBER(3) NOT NULL,
    STU_NO CHAR(5 BYTE) NOT NULL,
    SUB_CODE CHAR(1) NOT NULL,
    CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_NO) REFERENCES STUDENT(STU_NO),
    CONSTRAINT FK_ENROLL_SUBJECT FOREIGN KEY(SUB_CODE) REFERENCES OBJECT(SUB_CODE)
);